name: Full Deploy (Terraform + Function)

on:
  workflow_dispatch:
    inputs:
      run_terraform:
        description: "Run Terraform?"
        required: true
        default: "true"
      run_function:
        description: "Deploy Function?"
        required: true
        default: "true"

jobs:
  terraform:
    if: ${{ github.event.inputs.run_terraform == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: terraform init
        working-directory: terraform

      - run: terraform apply -auto-approve
        working-directory: terraform

  deploy-function:
    needs: terraform
    if: ${{ github.event.inputs.run_function == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/functions-action@v1
        with:
          app-name: poc-blob-func-123
          package: function
